report:
  expiredTime: 2
  incrementTime: 1
  decrementTime: 1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final_project_db
    driver-class-name: org.postgresql.Driver
    username:
    password:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
