#app:
#  users:
#    - userName: user
#      password: $2a$10$4xsEI09vI2RoLUzpoSGxzevbR33SBnIsXgjISzhUP3TOqxOFqFcZq
#      authorities:
#        - ROLE_USER
#
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/final_project_db
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true